### ISSUE TITLE
Entities for Toggle

### ISSUE THREAD

**Issue by crankycowboy** [BigThunderSR/homeassistant-addons-onstar2mqtt#315]
I've installed the addon and configured mqtt. A LOT of entities were added, but they are all mostly sensors (ie. ambient air, fuel level, gas range, tire etc). I don't see a toggle for actually starting my car or locking/unlocking doors. Am I missing something?  I've combed through the documentation, but I'm not seeing anything. I tried to sort this out myself before bothering anyone. Any help is appreciated.

**Comment by crankycowboy** [comment]
Thank you @BigThunderSR , I should have mentioned that I followed the documentation and tried that script. I can run the script and it looks like it goes through, but the vehicle never starts.

**Comment by crankycowboy** [comment]
Thanks again for the response @BigThunderSR  I initiated the script and then recorded the error (I should mention that when the addon connects to the car through mqtt initially, and the polling all seem to work as well as related sensors:

`error: Error {"error":{"error":{"message":"Command Failure","request":{"body":"{}","contentType":"application/json; charset=UTF-8","headers":{},"method":0,"url":"https://api.gm.com/api/v1/account/vehicles/3GNAXNEG5RL113954/requests/46736709855"},"response":{"data":{"commandResponse":{"body":{"error":{"code":"ONS-216","description":"Unable to establish packet session to the vehicle"}},"completionTime":"2023-12-31T14:31:07.194Z","requestTime":"2023-12-31T14:30:07.097Z","status":"failure","type":"diagnostics","url":"https://api.gm.com/api/v1/account/vehicles/3GNAXNEG5RL113954/requests/46736709855"}},"headers":{"connection":"keep-alive","content-type":"application/json;charset=UTF-8","date":"Sun, 31 Dec 2023 14:31:10 GMT","request-context":"appId=cid-v1:a7e19842-5b19-4b47-a9cf-85cc6e87a746","transfer-encoding":"chunked"},"status":200,"statusText":"OK"},"stack":"Error: Command Failure\n    at RequestService.<anonymous> (/app/node_modules/onstarjs/dist/index.cjs:558:35)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/onstarjs/dist/index.cjs:26:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}},"timestamp":"2023-12-31 08:31:10"}`

**Comment by crankycowboy** [comment]
Thank you. I see that is indeed the error I'm getting; however, I've tried starting via mqtt immediately after shutting the car off, 15 minutes after shutting off and after it sat all night and all deliver the same error. Looking through the logs, it appears that it returns that error every time  it "pings" my car at the set intervals. I completely stopped my HA vm and restarted and now I have a really weird phenomenon.  In the onstar addon log, I'm no longer getting errors after I restarted HA, it's returning all the data again, and has beenfor about 2 hours without errors. However, the data isn't getting passed to mqtt for some reason. I tried deleting the instance in mqtt and restarted and it detected my vehicle and all the sensors, but they all say "unavailable". Any suggestions what I can do to pass the data to mqtt again? My mqtt credentials are all correct. Any help is greatly appreciated.

**Comment by crankycowboy** [comment]
Thank you very much for trying to help. I'll give it a few days to see what happens. I appreciate your help.

**Comment by crankycowboy** [comment]
I just edited my post to respond as well, haha

**Comment by crankycowboy** [comment]
That didn't work. It's really odd. I may just remove the addon and try from the beginning again.  I've attached a couple pictures showing that mqtt shows unavailable, but what's weird is if I go into the mqtt logs for my vehicle, it looks like it's receiving the data for all the sensors, the sensors just show unavailable.  See pictures for reference.
![message publishing](https://github.com/BigThunderSR/homeassistant-addons-onstar2mqtt/assets/2176738/eee94578-b39f-4e65-bdc7-1e0435208a26)
![received messages](https://github.com/BigThunderSR/homeassistant-addons-onstar2mqtt/assets/2176738/561b2402-eced-4a2a-9d68-d0d87ba4b292)
![unavailable](https://github.com/BigThunderSR/homeassistant-addons-onstar2mqtt/assets/2176738/99f3f807-c14f-463a-a82c-8eaae7dd37ff)

**Comment by crankycowboy** [comment]
Good point, I'll work on that. I actually scrolled down a bit to prevent my other more important data from being exposed, but forgot about the VIN.

**Comment by crankycowboy** [comment]
Where would I find that value?

**Comment by crankycowboy** [comment]
I'm looking in mosquitto, where would that value be within the broker?  Sorry for the hassle by the way.

**Comment by crankycowboy** [comment]
Yeah, I have that installed and that's one of the ways I was able to verify that the addon is actually talking to mqtt. I just don't know where to find that particular value

**Comment by crankycowboy** [comment]
I think I may have found it....I may have also found what may be my problem. In the "mqtt prefix" I originally had it set as "equinox" but then changed it to just "onstar" and republished and then restarted. Both instances are showing within explorer one shows available=true and the other shows available=false.  The one that shows false is the one I originally had, but I can't help but think that maybe this is the issue? What are your thoughts?

**Comment by crankycowboy** [comment]
Geez, that was it.  I'm so sorry, you had to spend so much time helping a dip$hit.  I'm back to trying to see if I can start it via the script again. Thanks for all your patience.

**Comment by crankycowboy** [comment]
@BigThunderSR I was able to FINALLY get the car to start via the script.  Thank you for your help. I really appreciate all the time you spent.
