### ISSUE TITLE
Error trying to start 24 Chevy Silverado 2500.....

### ISSUE THREAD

**Issue by jarjarfinks** [BigThunderSR/homeassistant-addons-onstar2mqtt#364]
I installed your addon and it appears to be configured correctly when I look at the logs. Then when I run your example script for starting the car, it shows the following in the log:

`error: Error {"error":{"error":{"message":"Command Failure","request":{"body":"{}","contentType":"application/json; charset=UTF-8","headers":{},"method":0,"url":"https://api.gm.com/api/v1/account/vehicles/1GC4YPEY1RF101205/requests/47519256293"},"response":{"data":{"commandResponse":{"body":{"error":{"code":"ONS-216","description":"Unable to establish packet session to the vehicle"}},"completionTime":"2024-01-26T16:13:19.643Z","requestTime":"2024-01-26T16:12:18.607Z","status":"failure","type":"diagnostics","url":"https://api.gm.com/api/v1/account/vehicles/1GC4YPEY1RF101205/requests/47519256293"}},"headers":{"connection":"keep-alive","content-type":"application/json;charset=UTF-8","date":"Fri, 26 Jan 2024 16:13:23 GMT","request-context":"appId=cid-v1:a7e19842-5b19-4b47-a9cf-85cc6e87a746","transfer-encoding":"chunked"},"status":200,"statusText":"OK"},"stack":"Error: Command Failure\n    at RequestService.<anonymous> (/app/node_modules/onstarjs/dist/index.cjs:558:35)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/onstarjs/dist/index.cjs:26:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}},"timestamp":"2024-01-26 09:13:23"}`

I have no idea how to diagnose this. Also something to note, when I try to copy the YAML in the YAML editor in HA, it puts escape characters in place of some of the characters in the "payload:" portion of the code. i.e. this:
`payload: '{"command": "startVehicle"}'` turns into `payload: "{\"command\": \"startVehicle\"}"`

Not sure if that's the issue, but please let me know what I should do. 

Also, I don't see any entities created for this addon when it's configured, did I do something wrong?

**Comment by jarjarfinks** [comment]
Nevermind, solved all my issues, I'm an idiot. Forgot to add MQTT as an integration lmao. Thanks for the awesome addon!
