### ISSUE TITLE
"ONS-900" error from GM API

### ISSUE THREAD

**Issue by darrendavid** [BigThunderSR/homeassistant-addons-onstar2mqtt#399]
just updated to the latest 1.10.0 and not getting any API responses. I'm seeing the following error in my logs:

```
{
	"error": {
		"error": {
			"message": "Command Failure",
			"request": {
				"body": "{}",
				"contentType": "application/json; charset=UTF-8",
				"headers": {

				},
				"method": 0,
				"url": "https://api.gm.com/api/v1/account/vehicles/<REDACTED>/requests/36394112778"
			},
			"response": {
				"data": {
					"commandResponse": {
						"body": {
							"error": {
								"code": "ONS-900",
								"description": "Unknown system error"
							}
						},
						"completionTime": "2024-03-13T00:23:57.683Z",
						"requestTime": "2024-03-13T00:23:40.548Z",
						"status": "failure",
						"type": "diagnostics",
						"url": "https://api.gm.com/api/v1/account/vehicles/<REDACTED>/requests/36394112778"
					}
				},
				"headers": {
					"connection": "keep-alive",
					"content-type": "application/json;charset=UTF-8",
					"date": "Wed, 13 Mar 2024 00:24:02 GMT",
					"request-context": "appId=cid-v1:a7e19842-5b19-4b47-a9cf-85cc6e87a746",
					"transfer-encoding": "chunked"
				},
				"status": 200,
				"statusText": "OK"
			},
			"stack": "Error: Command Failure\n    at RequestService.<anonymous> (/app/node_modules/onstarjs/dist/index.cjs:558:35)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/onstarjs/dist/index.cjs:26:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
		}
	},
	"timestamp": "2024-03-12 14:24:02"
}

```

**Comment by darrendavid** [comment]
Hrm, we just drove the car and it's still returning that error. Anything else to check?

**Comment by darrendavid** [comment]
No updates while driving. I've restarted the Add-on and even tried a new UUID. No luck.

**Comment by bordelonkj** [comment]
I'm also having this same issue but agree that it appears to be an API problem. I'm able to send commands and receive a successful response from both the addon (v1.10.0) and the myChevrolet app but neither are able to poll for the vehicle's current status. FYI downgrading the addon to v1.8.0 exhibited the same error. I'm in the central US in case there's a geographical component.

Guess I'll wait on GM to get their act together.

**Comment by darrendavid** [comment]
Confirmed, I indeed have a Bolt. FWIW the script had been working fine up until about a week ago.

**Comment by ejpenney** [comment]
Confirmed, also a Bolt owner.  I'll second @bordelonkj, it does appear _getLocation_, _unlockDoor_, etc. are still working, it's just device diagnostics that aren't.  I'm unable to verify the Node Red stuff as I don't have Node Red in my environment nor the bandwidth to set it up.  I'll also note I tried installed the michaelwoods add-on as well as the BigThunderSR versions and have consistent issues in both places.

The MyChevrolet app has been pestering me about a bunch of beta features for the Bolt, including Plug and Charge.  I'm worried the API may have _changed_, but as I also understand OnStar is-what-it-is, I'll take the wait-and-see for a few days...

**Comment by ejpenney** [comment]
I'm getting diagnostic data again today. Seems like the GM issue is resolved.

**Comment by darrendavid** [comment]
Same!
