### ISSUE TITLE
Stock at totp

### ISSUE THREAD

**Issue by thib5** [BigThunderSR/homeassistant-addons-onstar2mqtt#820]
Hi, i'm trying to activate totp on my onstar account. So i disable email verification, enable third party. it redirect me ton a gm page i log id than it redirect me on a microsoft page and there I don't know what to do... I try to login with a microsoft account I own but it gave me error message.

Thank you

**Comment by thib5** [comment]
Oh … so no way I can integrate my car into ha ? Why it’s not possible to log then put the code I received by email ?

**Comment by sam2kb** [comment]
It works! Thank you all. Feel free to use these instructions.

1. Open OnStar.com in a desktops browser 
2. Go to My Account in the top right corner 
3. Login with your email and password 
4. Click Account then scroll down to Login & Security 
5. Turn off Email Authentication
6. Turn on Third-Party Authenticator App
7. Copy TOTP then go and setup your TOTP app as usual
8. Paste TOTP secret in the addon config field 
9. Start add-on and enjoy!

**Comment by sam2kb** [comment]
Commands worked ok but the sensors didn't update until I started the car.

**Comment by thib5** [comment]
> It works! Thank you all. Feel free to use these instructions.
> 
> 1. Open OnStar.com in a desktop browser
> 2. Go to My Account in the top right corner
> 3. Login with your email and password
> 4. Click Account then scroll down to Login & Security
> 5. Turn off Email Authentication
> 6. Turn on Third-Party Authenticator App
> 7. Copy TOTP then go and setup your TOTP app as usual
> 8. Paste TOTP secret in the addon config field
> 9. Start add-on and enjoy!



I think as @BigThunderSR  said it does not work on canadian account... after I click on third-party app i saw that : 



![CleanShot 2024-11-24 at 14 31 32@2x](https://github.com/user-attachments/assets/ab48b885-5eff-4f2c-bd65-830ab37cc51e)

![CleanShot 2024-11-24 at 14 32 15@2x](https://github.com/user-attachments/assets/9b8ad7e7-21cd-4531-9cdb-05f1358bf6a4)

**Comment by lululombard** [comment]
@thib5 I have the exact same issue. I tried using the same or a different email address in that microsoft login but it does not matter it does not work.

**Comment by thib5** [comment]
@lululombard  Ok cool i'm not the only one ... you have a Canadian account ?

**Comment by lululombard** [comment]
@thib5 yes canadian account, I need to log in via chevrolet.ca because if I login to gm.com or onstar.com, all the links are a 404 including "account overview"

**Comment by thib5** [comment]
Yes same for me ... maybe we could try to contact onstar... I don't know when i will have the time to do it but i will put this in my to do list

**Comment by evilpig** [comment]
@BigThunderSR 

I am getting stuck here after generating the token json and booting the addon. 

https://github.com/samrum/OnStarJS/issues/233#issuecomment-2499264436

> Please see if this works for you:
> 
> [samrum/OnStarJS#233 (comment)](https://github.com/samrum/OnStarJS/issues/233#issuecomment-2499197442)

**Comment by thib5** [comment]
I hate not being able to do thing by my own but i could use some help...

I launch gmauth.exe and got the same warning some one had. from what i understand it's normal. but i can't find the token ...

**Comment by thib5** [comment]
IT WORKS !

**Comment by nhorvath** [comment]
@BigThunderSR I just wanted to say THANK YOU for keeping this going. the My Chevy app sucks so much!

**Comment by admiralfred** [comment]
@BigThunderSR I'm a Canadian user so I use the email verification with the token via the metheos method. It works fine but after a couple of days running I get this "error" in the log

info: Requesting diagnostics {"timestamp":"2025-02-03 16:40:42"}
Returned GM API token was missing vehicle information. Deleting existing tokens for reauth.
Authentication failed: Error: Only TOTP via "Third-Party Authenticator" is currently supported by this implementation. Please update your OnStar account to use this method, if possible.
    at GMAuth.<anonymous> (/app/node_modules/onstarjs2/dist/index.cjs:40666:23)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/onstarjs2/dist/index.cjs:43:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

it then renames the microsoft_tokens.json to microsoft_tokens.json.old and it stop working. If I rename it back to original name microsoft_tokens.json it works again.

Am I missing something?

Thanks
