### ISSUE TITLE
HA AddOn Won't Start

### ISSUE THREAD

**Issue by tmorris0221** [BigThunderSR/homeassistant-addons-onstar2mqtt#831]
After updating the TOTP in my configuration, I'm getting the following error in the logs and cannot get add-on to stay running.

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[14:29:10] INFO: Starting OnStar2MQTT for Tahoe...

onstar2mqtt@1.20.0 start
node src/index.js
info: OnStar Config:
info: MQTT Config:
info: !-- Starting OnStar2MQTT Polling --! {"timestamp":"2024-11-26 14:29:17"}
info: Requesting vehicles {"timestamp":"2024-11-26 14:29:17"}
Authentication failed: Error: Invalid base32 character in key
at TOTP.base32tohex (/app/node_modules/onstarjs2/dist/index.cjs:34421:23)
at TOTP.generate (/app/node_modules/onstarjs2/dist/index.cjs:34397:32)
at GMAuth. (/app/node_modules/onstarjs2/dist/index.cjs:34535:34)
at Generator.next ()
at fulfilled (/app/node_modules/onstarjs2/dist/index.cjs:43:58)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error: Main function error: {"error":{"message":"Invalid base32 character in key"},"timestamp":"2024-11-26 14:29:23"}
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by tmorris0221** [comment]
Was able to resolve by pasting my TOTP Secret into the configuration, not the actual return code given by my 3rd party app.
